### ISSUE TITLE
Problems running scons to build the active_countor module

### ISSUE THREAD

**Issue by joaopalavra** [ukalwa/melanoma-detection-python#2]
I did all of the steps in the Environment Setup but when I run scons to build the module this error appears:

B:\melanoma-detection-python>scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fobuild\active_contour.obj /c jni\active_contour.cpp /TP /Zm800 -nologo /EHsc /DBOOST_PYTHON_DYNAMIC_LIB /Z7 /Od /Ob0 /GR /MD
/wd4675 /Zc:forScope /Zc:wchar_t /nologo "/IC:\Program Files\Python37\include" /IB:\boost_1_62_0 "/IC:\Program Files\Python37\Lib\
site-packages\numpy\core\include" /IB:\opencv\build\include
active_contour.cpp
Unknown compiler version - please run the configure tests and report the results
c:\program files\python37\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated
NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
b:\melanoma-detection-python\jni\conversion.h(10): warning C4005: 'NUMPY_IMPORT_ARRAY_RETVAL': macro redefinition
c:\program files\python37\lib\site-packages\numpy\core\include\numpy\__multiarray_api.h(1541): note: see previous definition of 'NUMPY_IMPORT_ARRAY_RETVAL'
link /nologo /dll /out:active_contour.cp37-win_amd64.pyd /implib:active_contour.lib /LIBPATH:B:\boost_1_62_0\lib64-msvc-14.0 "/LIBPATH:C:\Program Files\Python37\libs" /LIBPATH:B:\opencv\build\x64\vc12\lib boost_python-vc140-mt-gd-1_62.lib opencv_features2d2410.lib ope
ncv_core2410.lib opencv_highgui2410.lib opencv_imgproc2410.lib build\ac_withoutedges_yuv.obj build\active_contour.obj build\activecontour.obj build\conversion.obj build\linked_list.obj
   Creating library active_contour.lib and object active_contour.exp
active_contour.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) struct _object * __cdecl boost::python::detail::init_module(struct PyModuleDef &,void (__cdecl*)(void))" (__imp_?init_module@detail@python@boost@@YAPEAU_object@@AEAUPyModuleDef@@P6AX
XZ@Z) referenced in function PyInit_active_contour
active_contour.cp37-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
scons: *** [active_contour.cp37-win_amd64.pyd] Error 1120
scons: building terminated because of errors.

**Comment by ukalwa** [comment]
Hello Joaopalavra,

The repository is compatible with Python 2.7 and looks like you are using Python 3.7. Please change it to Python 2.7 and let me know if it doesn't work.

I am closing the issue now, but if you get any errors, you can reopen the issue.

Thanks,
Upender
